"""Initial migration

Revision ID: 209232331821
Revises: 
Create Date: 2025-05-02 11:01:14.115674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209232331821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('category')
        batch_op.drop_column('video')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('video', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
